spring:
  profiles:
    active: release

auth.jwt:
  issuer: waffle
  jwtSecret: THIS_IS_THE_SECRET_KEY_FOR_THE_WAFFLE_SEMINAR2_ASSIGNMENT_SPRING_PROJECT
  jwtExpiration: 3600000
  
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/seminar?serverTimezone=UTC
    username: root
    password: seminar
  jpa:
    properties:
      hibernate:
        show_sql: true
    hibernate:
      ddl-auto: create
  
---
spring:
  config:
    activate:
      on-profile: release
  datasource:
    url: jdbc:mysql://database:3306/seminar?serverTimezone=UTC
    username: root
    password: seminar
  jpa:
    properties:
      hibernate:
        show_sql: false
    hibernate:
      ddl-auto: update